"""Dependency-free Wilvor operational domain semantics."""

from .current_set import (
    CURRENT_ALERT_STATES,
    CURRENT_ENCOUNTER_STATES,
    TERMINAL_ENCOUNTER_STATES,
    choose_latest_current_risk,
    index_current_hazard_versions,
    index_current_projections,
    index_latest_current_risks,
    is_current_aircraft,
    is_current_airport_status,
    is_current_alert,
    is_current_alert_at,
    is_current_encounter,
    is_current_hazard,
    is_current_projection,
    is_current_recommendation,
    is_current_recommendation_at,
    is_current_risk,
    is_lifecycle_active_alert,
    is_lifecycle_active_hazard,
    is_lifecycle_active_recommendation,
)


__all__ = (
    "CURRENT_ALERT_STATES",
    "CURRENT_ENCOUNTER_STATES",
    "TERMINAL_ENCOUNTER_STATES",
    "choose_latest_current_risk",
    "index_current_hazard_versions",
    "index_current_projections",
    "index_latest_current_risks",
    "is_current_aircraft",
    "is_current_airport_status",
    "is_current_alert",
    "is_current_alert_at",
    "is_current_encounter",
    "is_current_hazard",
    "is_current_projection",
    "is_current_recommendation",
    "is_current_recommendation_at",
    "is_current_risk",
    "is_lifecycle_active_alert",
    "is_lifecycle_active_hazard",
    "is_lifecycle_active_recommendation",
)
